### ISSUE TITLE
descriptive-munging no longer executing

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#33]
Chunk descriptive-munging is no longer executing, giving the following error on knit:

```R
processing file: index.qmd
  |....                           |  11% [descriptive-munging]                 Error in `UseMethod()`:
! no applicable method for 'inner_join' applied to an object of class "character"
Backtrace:
 1. dplyr::inner_join(BTSorensen, effect_Ids)
                                                                                                                                 


Quitting from lines 2418-2789 [descriptive-munging] (index.qmd)

Execution halted
```

Also, I note that this code is duplicated in SM2_EffectSizeAnalysis.qmd, however in the latter document, the objects are mostly subset. 

- [x] Shift funs into ManyEcoEvo (https://github.com/egouldo/ManyEcoEvo/issues/24)
- [x] Shift code into ManyEcoEvo targets pipeline (https://github.com/egouldo/ManyEcoEvo/issues/24)
- [x] Retain manipulation only needed to extract required data in both index.qmd and M2_EffectSizeAnalysis.qmd, culling the remainder
- [x] Ensure dependent object calls execute (specifically in-text R expressions and tables etc. #32 )
