### ISSUE TITLE
check back-transformation on yi euc meta-analysis

### ISSUE THREAD

**Issue by egouldo** [egouldo/ManyAnalysts#63]
- [x] ensure that plots for euc variables don't repeat back-transformations unnecessarily (meta-analysis should already be on stem-count scale, i.e. not standardised as per `Z_VZ_preds()`), however, we should continue logging the outcome variable.
- [ ] Ensure (if) any logging of response vars is done prior to fitting models, that these are reported as a deviation in manuscript (I *think* we only transform them for plotting purposes).
- [ ] Update preregistration deviation section. See issue in non-anonymised repository for discussion / paper-trail on decision: https://github.com/metamelb-repliCATS/ManyAnalysts/issues/194

**Comment by egouldo** [comment]
- [ ] When egouldo/ManyEcoEvo#88 is closed, this issue can be addressed.

**Comment by egouldo** [comment]
- [ ] Note, need to shift log-transformation (if needed) into ManyEcoEvo pkg.
- [x] first, try running plot on non-standardised but back-transformed data
